apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-storage
spec:
  replicas: 2
  selector:
    matchLabels:
      app: data-storage
  template:
    metadata:
      labels:
        app: data-storage
    spec:
      containers:
      - name: data-storage
        image: data-storage
        imagePullPolicy: Never
        env:
          - name: MONGO_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongo-creds
                key: username
          - name: MONGO_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo-creds
                key: password
          - name: MONGO_SERVER
            valueFrom:
              configMapKeyRef:
                name: dsbd-map
                key: mongo_server
          - name: KAFKA_TOPIC
            valueFrom:
              configMapKeyRef:
                name: dsbd-map
                key: kafka_topic
          - name: KAFKA_BROKER
            valueFrom:
              configMapKeyRef:
                name: dsbd-map
                key: kafka_broker
